### ISSUE TITLE
Conflict with The Aether mod, unable to generate aether portal

### ISSUE THREAD

**Issue by alsodoze** [Yoghurt4C/BetterWithPatches#2]
water will simply flow down rather than generate aether portal in glowstone structure

**Comment by Yoghurt4C** [comment]
that's cool but I don't touch any part of block interaction or propagation

**Comment by alsodoze** [comment]
have test a bit, i think you are right. It seems like is better with mod itself cause it.

**Comment by Yoghurt4C** [comment]
does it still happen if bwm's "hardcore buckets" config option is disabled?

**Comment by Yoghurt4C** [comment]
didn't mean to close but I'll look at it later if you say which aether it's fucking with (there's like 2 on 1.7)

**Comment by alsodoze** [comment]
> does it still happen if bwm's "hardcore buckets" config option is disabled?

yeah, that fix it

**Comment by alsodoze** [comment]
and sorry for my vague description. I mean  this one at first: https://www.curseforge.com/minecraft/mc-mods/aether
But later i found out both are having this issue if "hardcore buckets" set to true.

**Comment by Yoghurt4C** [comment]
Really Fixed in https://github.com/Yoghurt4C/BetterWithPatches/commit/0d01841a719773d90d5890f10862a56832d63d68
