### ISSUE TITLE
Crashes when Alfheim is present

### ISSUE THREAD

**Issue by 062regrahc** [Yoghurt4C/BetterWithPatches#3]
https://pastebin.com/iLEA4h3a

**Comment by Yoghurt4C** [comment]
not my problem

**Comment by Yoghurt4C** [comment]
nevermind it is my problem

**Comment by Yoghurt4C** [comment]
brown bricked in https://github.com/Yoghurt4C/BetterWithPatches/commit/ebd01056e9b5635c9e62e131ed682b1599317a5b
